site_name: Software Factory
nav:
  - Intro: index.md
  - Factory Process: 
    - Introduction: handbook/process/intro.md
  - For Developers: 
    - Introduction: handbook/developer/intro.md
  - For Operators: 
    - Introduction: handbook/platform/intro.md
    
theme: readthedocs
