site_name: Software Factory
nav:
  - Home: index.md
  - Handbooks: 
    - Factory Process: handbook/process.md
    - For Developers: handbook/developer.md
    - For Operators: handbook/platform.md
theme: readthedocs
